name: agconnect_crash
description: Flutter plugin for AppGallery Connect Crash SDK.
version: 2.0.0
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-crash-introduction

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <3.39.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcrash
        pluginClass: AGConnectCrashPlugin
      ios:
        pluginClass: AGConnectCrashPlugin
