name: agconnect_clouddb_example
description: Demonstrates how to use the agconnect_clouddb plugin.

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  agconnect_clouddb:
    path: ../
  agconnect_auth: 1.9.0+300

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
