name: agconnect_core
description: Flutter plugin for AppGallery Connect Core SDK.
version: 2.0.0+002
homepage: https://www.huawei.com

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcore
        pluginClass: AGConnectCorePlugin
      ios:
        pluginClass: AGConnectCorePlugin
