name: agconnect_appmessaging
description: You can use App Messaging of AppGallery Connect to send relevant messages to target users.
homepage: https://developer.huawei.com/consumer/en/agconnect/
version: 2.0.0+002

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agc.flutter.appmessaging
        pluginClass: AgconnectAppmessagingPlugin
      ios:
        pluginClass: AgconnectAppmessagingPlugin
